### ISSUE TITLE
Undefined index in Omeka v3.0

### ISSUE THREAD

**Issue by J-Nistler** [DBinaghi/plugin-HonorThyLibrarians#1]
Displays error messages on the rendered "Librarian" page on the front end:

--------------------------------

The following people have contributed to this website.

Notice: Undefined index: arg in /var/www/omeka/final/plugins/HonorThyLibrarians/views/helpers/Librarians.php on line 38

Notice: Undefined index: arg1 in /var/www/omeka/final/plugins/HonorThyLibrarians/views/helpers/Librarians.php on line 40

--------------------------------

Under that, librarians seem to display correctly in a table as designed with no other issues noted. Only issue is displayed message. Running Omeka 3.0, PHP 7.4.3, and plugin 1.2.

**Comment by DBinaghi** [comment]
Hi.
Thanks for your warning. Bug has been fixed in new release 1.3.

**Comment by J-Nistler** [comment]
Applied the new release (1.3) and everything works flawlessly! Thank you!
